# Site wide config
title                 : Endangered Data Week
description           : "<strong>raising awareness</strong> of threats to publicly available data; <strong>exploring</strong> the power dynamics of data creation, sharing, and retention; and <strong>teaching</strong> ways to make endangered data more accessible and secure"
tag                   : "bringing together researchers, journalists, librarians, technologists, and community partners to discuss data analysis, creation, sharing, retention, preservation, and security"
date                  : "(Virtual) Endangered Data Week is September 21-25, 2020"
url                   : "http://endangereddataweek.org"
repository            : "https://github.com/endangereddataweek/endangereddataweek.org"
twitter_username      : "clirdlf"
twitter_hash          : "EndangeredData"

google-tracking-id    : "UA-93198655-1"

# Jekyll config
markdown              : kramdown
kramdown:
  toc_levels          : 1..3
  hard_wrap           : false
  auto_ids            : true
future                : true
show_drafts           : false
highlighter           : rouge

permalink: pretty

collections:
  events:
    output: true # generate a page for each document
    permalink: /:collection/:path/

# Navigation
navigation:
  - title: about
    url: /about/
  - title: events & map
    url: /map/
  - title: past events
    url: /archives/
  - title: news
    url: /news/

exclude: ['vendor', 'templates','node_modules', '.gitignore', '.env', 'Gemfile*', 'gulpfile.js', 'Makefile', 'package.json', 'Rakefile', 'README.md']
sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
