# Site wide config
title                 : Endangered Data Week
description           : "Bringing awareness to different types of threats to publicly available data, engage with the power dynamics involved in data creation, sharing, and retention, and to make endangered data more secure and accessible."
tag                   : "Bringing together researchers, journalists, librarians, technologists, and community partners to discuss data analysis, creation, sharing, retention, preservation, security."
date                  : "April 17-21 2017"
url                   : "http://endangereddataweek.org"
repository            : "https://github.com/endangereddataweek/endangereddataweek.org"

# Jekyll config
markdown              : kramdown
kramdown:
  toc_levels          : 1..3
  hard_wrap           : false
  auto_ids            : true
future                : true
show_drafts           : false
highlighter           : rouge

collections:
  events:
    output: true # generate a page for each document
    permalink: /:collection/:path/

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
