markdown: kramdown
title: Endangered Data Week
description: "Bringing awareness to different types of threats to publicly available data, engage with the power dynamics involved in data creation, sharing, and retention, and to make endangered data more secure and accessible."
tag: "Bringing together researchers, journalists, librarians, technologists, and community partners to discuss data analysis, creation, sharing, retention, preservation, security."
date: "April 17-21 2017"
url: "http://endangereddataweek.org"